### ISSUE TITLE
[RFC] Zotino/Fastino break out

### ISSUE THREAD

**Issue by jordens** [sinara-hw/HD68_BNC_Breakout#1]
In most cases it is best to integrate the HD68 connector into the application and not use 32 BNC cables to connect Fastino/Zotino to the experiment. Yet people do it anyways at least for prototyping, debugging, or testing.
We've had the need a couple times already for a simple HD68-BNC break-out. The EDGE series of modules doesn't have a HD68 connection (that might be one solution). The HD68-IDC+4xIDC-BNC+front-panels+IDC cables+case is surprisingly costly. Overall it's probably much easier to make a straight 1xHD68 to 32xBNC break out with minimal mechanical complexity:

* BNC connectors as in https://github.com/sinara-hw/Banker_EDGE_2_BNC and/or MCX connectprs (variant?)
* A HD68 connector preferrably perpendicular to the board (for simpler mechanical design) like the BNC connectors
* No front panel, make the PCB the panel (as in the EDGE series).
* Find a simple case that the PCB can slide or be screwed into. It's only task is to cover the PCB underside. Or alternatively just mount the PCB onto a simple strengthener (preferrably COTS though and not custom).
* Use a standard board size that fits standard cases. Add common mounting holes.

@gkasprow What do you think?

**Comment by gkasprow** [comment]
OK. I'm curious why all these people use these old large connectors instead of mcx :)

**Comment by gkasprow** [comment]
There is already 32-channel [MCX adapter](https://github.com/sinara-hw/IDC_MCX_Adapter/wiki) for Fastino/Zotino that can be mounted on top of the Fastino board as a mezzanine

**Comment by jordens** [comment]
The problem with the IDC-MCX is that it hasn't been manufactured yet (AFAIK), that is mechanically relatively complex (two boards and a link between) and that it (compared to this hypothetical HD68-BNC) requires a panel plus a crate plus IDC cables plus the HD68-IDC adapter: the goal is to use the HD68 cable to get away from the rack but then break out in proximity to the experiment. Front panel space inside the crate (where Fastino/Zotino are) is at a premium.
I'd also prefer MCX but the dominant legacy cable is BNC or SMA. Maybe MCX/BNC as a variant?

**Comment by jordens** [comment]
I'm not complaining about the IDC-MCX adapter at all, especially since I instigated it at least in part. Just trying to best respond to practical use cases.

**Comment by gkasprow** [comment]
@jordens, what about such a design?
The BNC pitch is 20mm.
Under the main PCB, there is another 100% copper-filled PCB electrically connected with main PCB GND
![image](https://user-images.githubusercontent.com/4325054/209976877-0821eba0-a050-4130-82df-c73e7277aa29.png)

**Comment by jordens** [comment]
Looks good to me. Is there a spacer between the two for the solder joints of the tht parts?

**Comment by jordens** [comment]
Thanks a bunch.
Mounting holes and mcx variant would be my last items.

**Comment by jordens** [comment]
If you can make the PCB a 100 by 160 mm with Eurocard mounting holes (hd68 through the panel) that would be a nice option (mounting hardware and panels not supplied by default)

**Comment by gkasprow** [comment]
This is Eurocard size, 24x16 grid pattern
![image](https://user-images.githubusercontent.com/4325054/210014705-7400c5d2-9c31-4399-b9ba-7d1390a846ff.png)
Sure, the idea is to use SMT distances and M3 screws that can be fitted with rubber stands.

**Comment by gkasprow** [comment]
the MCX can be mounted rotated by 45 degrees
![image](https://user-images.githubusercontent.com/4325054/210014872-82a67dc3-78d5-47fa-8e0e-f6bd03b6ddc2.png)

**Comment by jordens** [comment]
Looks good, if that's not an issue with routing the center pin.
For sufficient rigidity (MCX pluggind and pulling), this will probably benefit from at least one additional spacer+rubber pad in the center of the PCB.
Also is the solder stop on the lower PCB hard enough to not be scratched by the pins of the top PCB, especially in the center where they might touch with some connector force?

**Comment by gkasprow** [comment]
Do we want one design with the front panel, bottom plate, and rubber stands?
Or two assembly options, one stand-alone with a bottom plate and rubber stands and another with just the front panel?
Plus, MCX/BNC makes four assembly options...

**Comment by gkasprow** [comment]
We need to go for M2.5 because the front panels use such screws.
Then we glue rubber bumps to the bottom side of the insulating plate
![image](https://user-images.githubusercontent.com/4325054/210019892-a22560c1-4eb7-4109-89a2-21dcc7d11259.png)

**Comment by gkasprow** [comment]
One can also use half of a [standard extruded enclosure](https://www.farnell.com/datasheets/1933057.pdf) as a base...

**Comment by jordens** [comment]
I'd go for two variants (BNC/mcx) and two mounting designs, the first being default:

* [Standard plastic cover](https://elektronik.heitec.de/en/packaging/components-accessories/front-panels-handles/plastic-covers-for-pcbs) (or [Schroff](https://www.digikey.com/en/products/detail/schroff/61000007/4210082)), rubber bumps on the plastic cover and no panel, it's not the sturdiest but the simplest solution 
* A standard half enclosure, bumps on the enclosure and a panel that fits the half enclosure to fix the PCB in place and cover the hd68

**Comment by jordens** [comment]
Or [the common Hammond enclosure with the slide-out panel](https://www.digikey.de/de/products/detail/hammond-manufacturing/1455L1602/1090709) which already includes rubber bumps. Just needs checking that the connectors don't interfere with the slide-in rails.

**Comment by jordens** [comment]
Eyeballing this, both enclosures (half shell and Hammond) should work with your design. But let's aim for the simple solution first (standard M2.5 pattern, the standard plastic cover, no rack mounting hardware, just the 4 screws and nuts to attach the cover, no panels, but rubber bumps). If we can get that manufactured it would be a useful tool for many.

**Comment by dhslichter** [comment]
Just a comment from our group -- likely we would prefer something that is not rack-mounted, but instead mounts behind a front panel and uses a die-cast aluminum box like [this](https://www.digikey.com/en/products/detail/hammond-manufacturing/1590D/131021) to enclose things around the back (replace the lid with custom front panel with chromated back face). Better EMI shielding generally than one gets with plastic or extruded anodized enclosures, and simple. The BNC/MCX and HD68 would all just come through holes in the custom front panel. If there is a dual footprint for the HD68 (horizontal/vertical) it would be easy to swap among these configurations.

**Comment by jordens** [comment]
@gkasprow could you make a release candidate for review?

**Comment by gkasprow** [comment]
first variant: BNC
![obraz](https://user-images.githubusercontent.com/4325054/222447259-4a97bd42-32ee-482d-a3fc-d7540b655920.png)
second variant : MCX
![obraz](https://user-images.githubusercontent.com/4325054/222449385-62b4c234-b36e-417a-8462-ca36e484a4fb.png)
![obraz](https://user-images.githubusercontent.com/4325054/222449441-e920b32e-0da5-4e1c-bc71-4f00f281f5db.png)

**Comment by jordens** [comment]
* I believe the footprint of the two connectors is the same except for a 0.6 mm shift of the two shield pins. Can we put the two footprints on top of each other (with a slightly enlarged PTH for the shield pins)?
* DNP the panel and hardware variant by default. Just the bottom cover and the screws for the cover.
* There are two inner layers that we don't need. These also appear to have stray thermals for the connectors.
* Put the routing onto the bottom layer (currently on top).

**Comment by gkasprow** [comment]
>   I believe the footprint of the two connectors is the same except for a 0.6 mm shift of the two shield pins. Can we put the two footprints on top of each other (with a slightly enlarged PTH for the shield pins)?

I just finished all details including mechanical designs of the panels and enclosure. I can make the hole bigger but won't find enough time soon to redesign all mechanics.

>    DNP the panel and hardware variant by default. Just the bottom cover and the screws for the cover.

ok

>    There are two inner layers that we don't need. These also appear to have stray thermals for the connectors.

I will try but need to connect metal case with GND

>    Put the routing onto the bottom layer (currently on top).

we have routing on both layers and one cannot escape from connectors with single layer

**Comment by gkasprow** [comment]
I removed the inner layers so we have 2-layer PCB.

**Comment by jordens** [comment]
* Ok. Leave the HD68 connectos as is.
* Ack the routing issue. I had looked at a partially routed version.
* ~~I don't get the thermals. In the "bare" variant without a case, they are not needed (there is no case). We don't have them for IDC-SMA or IDC-BNC or IDC-MCX either. Why don't the other IDC modules do this? Even with a case, why would you choose precisely this point here to short everything together and not e.g. the HD68 connector (easing routing) or on the Fastino/Zotino side? I'd like to see the thermals removed. As mentioned I don't see the point in the case anyway (unclear what the goal, target, or quantitative benefits are, given the use case and usually absent shielding on feedthroughs and chambers or inside the Sinara crate, the effort here seems pointless).~~

**Comment by jordens** [comment]
Ah. Sorry. I overlooked that you had isolated shield islands on the bottom layer. All good with the thermals.
I'm happy with this. Good to go from my side.

**Comment by jordens** [comment]
One important thing though: The labels should be 0-indexed and renamed ("IO0" to "IO31" instead of "OUT1" to "OUT32")
And the board label should be "HD68 to BNC/MCX adapter".

**Comment by jordens** [comment]
And the hole to change to elongated would have been the one on the angled connector (J1), not the one on the vertical one (J66 can not received an angled connector).

**Comment by gkasprow** [comment]
I was thinking about indexing but in Fastino/Zotino we have it from 1 due to Altium limitations...
I can make them from 0 as in the entire Sinara family

**Comment by gkasprow** [comment]
fixed

**Comment by jordens** [comment]
On Fastino and Zotino the silkscreen semantic labels are 0-indexed (as in "CH0"), as are all the panels and I think also all the other projects. The refdes for parts and groups/sheet repetitions etc. can be whatever you want.

**Comment by jordens** [comment]
I'd suppress refdes silkscreen for this project here, the semantic labels are sufficient.

**Comment by gkasprow** [comment]
I made a release https://github.com/sinara-hw/HD68_BNC_Breakout/releases/tag/v1.0rc4

**Comment by jordens** [comment]
Looks good to me. Thanks!

**Comment by jordens** [comment]
produced and tested
